name: API YamDB workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt
      
      - name: Test PEP8 and run pytests
        run: |
          python -m flake8
          python -m pytest
    
  # build_and_push_to_dockerhub:
  #   runs-on: ubuntu-latest
